# Generated by Django 2.0.7 on 2018-07-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='question_text',
            new_name='name_text',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_text',
            new_name='title_text',
        ),
    ]
